const sampleListings = [
  {
    title: "Baga Beach Party Villa",
    description: "A lively villa just minutes from Baga Beach, perfect for groups who want both relaxation and nightlife. Enjoy a private pool and spacious living areas.",
    image: { url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" }
    ],
    price: 7200,
    location: "Goa",
    country: "India",
    geometry: { type: "Point", coordinates: [73.7625, 15.2993] },
    category: "Beaches",
    propertyType: "Villa",
    amenities: ["WiFi", "Pool", "AC", "Parking", "Kitchen"],
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    houseRules: ["No loud music after 10PM", "Valid ID required", "No pets"],
    cancellationPolicy: "Moderate",
    cleaningFee: 1200,
    serviceFee: 900,
    isAvailable: true,
    accessibilityNotes: "Ground floor access available.",
    checkInInstructions: "Caretaker will assist on arrival."
  },

  {
    title: "Calangute Cozy Beach Stay",
    description: "A budget-friendly homestay close to Calangute Beach with all basic comforts. Ideal for couples and solo travelers.",
    image: { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" }
    ],
    price: 2600,
    location: "Goa",
    country: "India",
    geometry: { type: "Point", coordinates: [73.7630, 15.5439] },
    category: "Beaches",
    propertyType: "Homestay",
    amenities: ["WiFi", "AC", "Kitchen", "Parking"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No parties", "No smoking indoors", "Respect neighbors"],
    cancellationPolicy: "Flexible",
    cleaningFee: 600,
    serviceFee: 400,
    isAvailable: true,
    accessibilityNotes: "Easily accessible by road.",
    checkInInstructions: "Self check-in with lockbox."
  },

  {
    title: "Anjuna Sunset Beach House",
    description: "Enjoy stunning sunset views from this peaceful beach house near Anjuna. Perfect for a relaxed Goa vibe.",
    image: { url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" }
    ],
    price: 5200,
    location: "Goa",
    country: "India",
    geometry: { type: "Point", coordinates: [73.7437, 15.5730] },
    category: "Beaches",
    propertyType: "Beach House",
    amenities: ["WiFi", "AC", "Sea View", "Kitchen", "Parking"],
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    houseRules: ["No loud music late night", "No smoking indoors", "ID required"],
    cancellationPolicy: "Moderate",
    cleaningFee: 1000,
    serviceFee: 700,
    isAvailable: true,
    accessibilityNotes: "Few steps at entrance.",
    checkInInstructions: "Host will greet at property."
  },

  {
    title: "Candolim Luxury Pool Apartment",
    description: "Modern apartment with pool access located near Candolim Beach. Great for small groups looking for comfort and style.",
    image: { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" }
    ],
    price: 4800,
    location: "Goa",
    country: "India",
    geometry: { type: "Point", coordinates: [73.7597, 15.5170] },
    category: "Beaches",
    propertyType: "Apartment",
    amenities: ["WiFi", "Pool", "AC", "Parking", "Kitchen"],
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    houseRules: ["No parties", "Quiet hours after 11PM", "No pets"],
    cancellationPolicy: "Moderate",
    cleaningFee: 900,
    serviceFee: 600,
    isAvailable: true,
    accessibilityNotes: "Elevator available.",
    checkInInstructions: "Security will assist with check-in."
  },

  {
    title: "Morjim Peaceful Beach Homestay",
    description: "A quiet and serene Homestay near Morjim Beach, ideal for those looking to escape the crowd and relax.",
    image: { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" }
    ],
    price: 3800,
    location: "Goa",
    country: "India",
    geometry: { type: "Point", coordinates: [73.7350, 15.6244] },
    category: "Beaches",
    propertyType: "Homestay",
    amenities: ["WiFi", "AC", "Garden", "Parking"],
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No loud music", "No smoking indoors", "Respect nature"],
    cancellationPolicy: "Flexible",
    cleaningFee: 700,
    serviceFee: 500,
    isAvailable: true,
    accessibilityNotes: "Flat entry access.",
    checkInInstructions: "Host will share directions prior arrival."
  },

  {
    title: "Starlight Mountain Homestay",
    description: "Experience peaceful Ladakhi nights under a sky full of stars. A cozy homestay with warm hospitality and local food.",
    image: { url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" }
    ],
    price: 2800,
    location: "Leh",
    country: "India",
    geometry: { type: "Point", coordinates: [77.5770, 34.1526] },
    category: "Hill Stations",
    propertyType: "Homestay",
    amenities: ["WiFi", "Heater", "Mountain View", "Parking"],
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No loud music", "Respect local culture", "ID required"],
    cancellationPolicy: "Flexible",
    cleaningFee: 700,
    serviceFee: 500,
    isAvailable: true,
    accessibilityNotes: "Located on slight elevation.",
    checkInInstructions: "Host will assist on arrival."
  },

  {
    title: "Pangong Lake View Camp",
    description: "Wake up next to the stunning Pangong Lake in this glamping tent. Ideal for adventurous travelers.",
    image: { url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" }
    ],
    price: 4200,
    location: "Leh",
    country: "India",
    geometry: { type: "Point", coordinates: [78.3917, 33.7253] },
    category: "Trending",
    propertyType: "Tent/Glamping",
    amenities: ["Bonfire", "Lake View", "Meals Included", "Parking"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No littering", "Follow timings", "No alcohol misuse"],
    cancellationPolicy: "Moderate",
    cleaningFee: 800,
    serviceFee: 600,
    isAvailable: true,
    accessibilityNotes: "Accessible via long drive.",
    checkInInstructions: "Pickup optional from Leh."
  },

  {
    title: "Leh Heritage Stone House",
    description: "Stay in a traditional Ladakhi stone house with modern comfort. A perfect blend of culture and convenience.",
    image: { url: "https://images.unsplash.com/photo-1582719471384-894fbb16e074", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" }
    ],
    price: 3500,
    location: "Leh",
    country: "India",
    geometry: { type: "Point", coordinates: [77.5770, 34.1526] },
    category: "Heritage",
    propertyType: "Homestay",
    amenities: ["WiFi", "Heater", "Kitchen", "Parking"],
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    houseRules: ["No smoking indoors", "Respect culture", "Quiet hours"],
    cancellationPolicy: "Moderate",
    cleaningFee: 900,
    serviceFee: 700,
    isAvailable: true,
    accessibilityNotes: "Some stairs inside property.",
    checkInInstructions: "Host will meet at entrance."
  },

  {
    title: "Snow Peak View Cabin",
    description: "A quiet cabin with panoramic views of snow peaks. Ideal for couples seeking isolation.",
    image: { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" }
    ],
    price: 3000,
    location: "Leh",
    country: "India",
    geometry: { type: "Point", coordinates: [77.5770, 34.1526] },
    category: "Hill Stations",
    propertyType: "Cabin",
    amenities: ["Heater", "Mountain View", "Bonfire", "Parking"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No parties", "No smoking", "Respect nature"],
    cancellationPolicy: "Flexible",
    cleaningFee: 700,
    serviceFee: 500,
    isAvailable: true,
    accessibilityNotes: "Remote location.",
    checkInInstructions: "Detailed map shared before arrival."
  },

  {
    title: "Luxury Ladakh Boutique Stay",
    description: "Premium boutique stay with modern interiors and traditional vibes. Perfect for comfortable high-altitude travel.",
    image: { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" }
    ],
    price: 8500,
    location: "Leh",
    country: "India",
    geometry: { type: "Point", coordinates: [77.5770, 34.1526] },
    category: "Trending",
    propertyType: "Villa",
    amenities: ["WiFi", "Heater", "Breakfast", "Parking", "Hot Water"],
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    houseRules: ["No loud music", "ID required", "No pets"],
    cancellationPolicy: "Strict",
    cleaningFee: 1200,
    serviceFee: 1000,
    isAvailable: true,
    accessibilityNotes: "Car accessible.",
    checkInInstructions: "Reception available."
  },

  {
    title: "Tea Garden View Homestay",
    description: "Wake up to endless tea plantations and misty hills. A peaceful retreat ideal for couples and nature lovers.",
    image: { url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" }
    ],
    price: 3200,
    location: "Munnar",
    country: "India",
    geometry: { type: "Point", coordinates: [77.0595, 10.0889] },
    category: "Hill Stations",
    propertyType: "Homestay",
    amenities: ["WiFi", "Mountain View", "Parking", "Bonfire"],
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No loud music", "No smoking indoors", "Respect nature"],
    cancellationPolicy: "Flexible",
    cleaningFee: 700,
    serviceFee: 500,
    isAvailable: true,
    accessibilityNotes: "Located on gentle slope.",
    checkInInstructions: "Host will guide via call."
  },
  {
    title: "Luxury Tea Estate Villa",
    description: "Stay inside a private tea estate with premium interiors and stunning valley views.",
    image: { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" }
    ],
    price: 9000,
    location: "Munnar",
    country: "India",
    geometry: { type: "Point", coordinates: [77.0595, 10.0889] },
    category: "Trending",
    propertyType: "Villa",
    amenities: ["WiFi", "AC", "Pool", "Parking", "Kitchen"],
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 3,
    houseRules: ["No parties", "ID required", "No pets"],
    cancellationPolicy: "Strict",
    cleaningFee: 1500,
    serviceFee: 1000,
    isAvailable: true,
    accessibilityNotes: "Car accessible.",
    checkInInstructions: "Caretaker available."
  },
  {
    title: "Eco Treehouse Retreat",
    description: "Stay elevated among trees with panoramic forest views. A unique eco-friendly experience.",
    image: { url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" }
    ],
    price: 4500,
    location: "Munnar",
    country: "India",
    geometry: { type: "Point", coordinates: [77.0595, 10.0889] },
    category: "Forests",
    propertyType: "Treehouse",
    amenities: ["WiFi", "Forest View", "Bonfire", "Breakfast"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No littering", "No smoking", "Respect wildlife"],
    cancellationPolicy: "Moderate",
    cleaningFee: 800,
    serviceFee: 600,
    isAvailable: true,
    accessibilityNotes: "Ladder/stairs access.",
    checkInInstructions: "Staff will assist."
  },
  {
    title: "Budget Hill Homestay",
    description: "Simple and clean homestay with valley views. Perfect for budget travelers.",
    image: { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" }
    ],
    price: 2200,
    location: "Munnar",
    country: "India",
    geometry: { type: "Point", coordinates: [77.0595, 10.0889] },
    category: "Hill Stations",
    propertyType: "Homestay",
    amenities: ["WiFi", "Parking", "Kitchen", "Mountain View"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No parties", "Quiet hours", "Respect host"],
    cancellationPolicy: "Flexible",
    cleaningFee: 500,
    serviceFee: 300,
    isAvailable: true,
    accessibilityNotes: "Easy access.",
    checkInInstructions: "Host greets on arrival."
  },
  {
    title: "Misty Valley Cabin",
    description: "A wooden cabin surrounded by foggy hills and silence. Perfect for a digital detox.",
    image: { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" }
    ],
    price: 3500,
    location: "Munnar",
    country: "India",
    geometry: { type: "Point", coordinates: [77.0595, 10.0889] },
    category: "Hill Stations",
    propertyType: "Cabin",
    amenities: ["WiFi", "Bonfire", "Mountain View", "Parking"],
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No loud music", "No smoking", "Respect environment"],
    cancellationPolicy: "Flexible",
    cleaningFee: 700,
    serviceFee: 500,
    isAvailable: true,
    accessibilityNotes: "Slight slope entry.",
    checkInInstructions: "Directions shared before arrival."
  },

  {
    title: "Lake Pichola Heritage Haveli",
    description: "Stay in a royal haveli overlooking Lake Pichola with stunning sunset views. Experience authentic Rajasthani architecture with modern comforts.",
    image: { url: "https://images.unsplash.com/photo-1590490360182-c33d57733427", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1582719471384-894fbb16e074", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" }
    ],
    price: 9000,
    location: "Udaipur",
    country: "India",
    geometry: { type: "Point", coordinates: [73.6827, 24.5854] },
    category: "Heritage",
    propertyType: "Heritage Haveli",
    amenities: ["WiFi", "AC", "Lake View", "Breakfast", "Parking"],
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    houseRules: ["No loud music after 10PM", "ID required", "Respect heritage property"],
    cancellationPolicy: "Strict",
    cleaningFee: 1500,
    serviceFee: 1000,
    isAvailable: true,
    accessibilityNotes: "Upper floors accessible via stairs.",
    checkInInstructions: "Reception desk available for check-in."
  },

  {
    title: "City Palace View Boutique Stay",
    description: "Wake up to views of the City Palace from your balcony. A stylish boutique stay in the heart of Udaipur.",
    image: { url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" }
    ],
    price: 5500,
    location: "Udaipur",
    country: "India",
    geometry: { type: "Point", coordinates: [73.6830, 24.5760] },
    category: "Heritage",
    propertyType: "Apartment",
    amenities: ["WiFi", "AC", "City View", "Kitchen", "Parking"],
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No parties", "No smoking indoors", "Quiet hours after 11PM"],
    cancellationPolicy: "Moderate",
    cleaningFee: 900,
    serviceFee: 600,
    isAvailable: true,
    accessibilityNotes: "Lift available.",
    checkInInstructions: "Self check-in via keypad."
  },

  {
    title: "Lakeside Luxury Villa Udaipur",
    description: "A premium villa with private pool and serene lake views. Perfect for luxury stays with family or friends.",
    image: { url: "https://images.unsplash.com/photo-1613977257363-707ba9348227", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" }
    ],
    price: 12000,
    location: "Udaipur",
    country: "India",
    geometry: { type: "Point", coordinates: [73.6500, 24.6000] },
    category: "Trending",
    propertyType: "Villa",
    amenities: ["WiFi", "Pool", "AC", "Parking", "Kitchen"],
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 3,
    houseRules: ["No loud music after 10PM", "ID required", "No pets"],
    cancellationPolicy: "Strict",
    cleaningFee: 1800,
    serviceFee: 1200,
    isAvailable: true,
    accessibilityNotes: "Car accessible property.",
    checkInInstructions: "Caretaker will assist on arrival."
  },

  {
    title: "Budget Homestay near Fateh Sagar",
    description: "A clean and affordable homestay near Fateh Sagar Lake. Ideal for travelers who want comfort on a budget.",
    image: { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" }
    ],
    price: 2300,
    location: "Udaipur",
    country: "India",
    geometry: { type: "Point", coordinates: [73.6670, 24.5850] },
    category: "Heritage",
    propertyType: "Homestay",
    amenities: ["WiFi", "Parking", "Kitchen", "AC"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No parties", "Respect host", "No smoking indoors"],
    cancellationPolicy: "Flexible",
    cleaningFee: 500,
    serviceFee: 300,
    isAvailable: true,
    accessibilityNotes: "Easy ground floor access.",
    checkInInstructions: "Host will welcome guests."
  },

  {
    title: "Aravalli Hills View Farm Stay",
    description: "Escape the city and stay in a peaceful farm surrounded by Aravalli hills. Perfect for nature lovers.",
    image: { url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" }
    ],
    price: 4000,
    location: "Udaipur",
    country: "India",
    geometry: { type: "Point", coordinates: [73.7200, 24.6200] },
    category: "Farms",
    propertyType: "Farm Stay",
    amenities: ["WiFi", "Garden", "Parking", "Bonfire", "Kitchen"],
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    houseRules: ["No loud music", "Respect nature", "No littering"],
    cancellationPolicy: "Moderate",
    cleaningFee: 800,
    serviceFee: 600,
    isAvailable: true,
    accessibilityNotes: "Accessible via village road.",
    checkInInstructions: "Directions shared prior arrival."
  },

  {
    title: "Ganga View Yoga Retreat",
    description: "A peaceful retreat overlooking the Ganga, perfect for yoga and meditation seekers. Wake up to river sounds and mountain air.",
    image: { url: "https://images.unsplash.com/photo-1502082553048-f009c37129b9", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" }
    ],
    price: 2800,
    location: "Rishikesh",
    country: "India",
    geometry: { type: "Point", coordinates: [78.2676, 30.0869] },
    category: "Pilgrimage",
    propertyType: "Homestay",
    amenities: ["WiFi", "Yoga Deck", "River View", "Kitchen"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No alcohol", "Silent hours after 9PM", "Respect spiritual environment"],
    cancellationPolicy: "Flexible",
    cleaningFee: 600,
    serviceFee: 400,
    isAvailable: true,
    accessibilityNotes: "Accessible via stairs.",
    checkInInstructions: "Host will share directions before arrival."
  },

  {
    title: "Luxury Riverside Camp",
    description: "Stay right beside the Ganga in a luxury riverside tent with bonfire nights. Perfect for adventure and relaxation.",
    image: { url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" }
    ],
    price: 4200,
    location: "Rishikesh",
    country: "India",
    geometry: { type: "Point", coordinates: [78.2900, 30.1200] },
    category: "Trending",
    propertyType: "Tent/Glamping",
    amenities: ["Bonfire", "River View", "Meals Included", "Parking"],
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No loud music after 10PM", "No littering", "Follow camp timings"],
    cancellationPolicy: "Moderate",
    cleaningFee: 800,
    serviceFee: 600,
    isAvailable: true,
    accessibilityNotes: "Short walk from parking area.",
    checkInInstructions: "Camp staff will guide on arrival."
  },

  {
    title: "Laxman Jhula Studio Apartment",
    description: "Modern studio apartment located near Laxman Jhula with easy access to cafes and ashrams.",
    image: { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" }
    ],
    price: 3500,
    location: "Rishikesh",
    country: "India",
    geometry: { type: "Point", coordinates: [78.2670, 30.1300] },
    category: "Trending",
    propertyType: "Apartment",
    amenities: ["WiFi", "AC", "Kitchen", "City View", "Parking"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No parties", "No smoking indoors", "Quiet hours after 11PM"],
    cancellationPolicy: "Moderate",
    cleaningFee: 700,
    serviceFee: 500,
    isAvailable: true,
    accessibilityNotes: "Lift available.",
    checkInInstructions: "Self check-in via keypad."
  },

  {
    title: "Forest Edge Cabin Retreat",
    description: "A quiet wooden cabin near the forest edge offering complete peace and nature immersion.",
    image: { url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" }
    ],
    price: 3000,
    location: "Rishikesh",
    country: "India",
    geometry: { type: "Point", coordinates: [78.3000, 30.1000] },
    category: "Forests",
    propertyType: "Cabin",
    amenities: ["WiFi", "Bonfire", "Forest View", "Parking"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No loud music", "No smoking", "Respect nature"],
    cancellationPolicy: "Flexible",
    cleaningFee: 600,
    serviceFee: 400,
    isAvailable: true,
    accessibilityNotes: "Short uphill walk required.",
    checkInInstructions: "Location shared via Google Maps."
  },

  {
    title: "Budget Ashram Stay Rishikesh",
    description: "Simple and peaceful ashram-style accommodation for spiritual travelers. Ideal for meditation and yoga retreats.",
    image: { url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" }
    ],
    price: 2000,
    location: "Rishikesh",
    country: "India",
    geometry: { type: "Point", coordinates: [78.2700, 30.0900] },
    category: "Pilgrimage",
    propertyType: "Homestay",
    amenities: ["WiFi", "Yoga Hall", "Simple Meals", "Parking"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No alcohol", "Maintain silence", "Follow ashram rules"],
    cancellationPolicy: "Flexible",
    cleaningFee: 500,
    serviceFee: 300,
    isAvailable: true,
    accessibilityNotes: "Ground floor access.",
    checkInInstructions: "Check-in at reception desk."
  },

  {
    title: "Riverside Stone Homestay Hampi",
    description: "A peaceful stone Homestay near the Tungabhadra river with stunning sunrise views. Perfect for slow travel and exploring ruins.",
    image: { url: "https://images.unsplash.com/photo-1582719471384-894fbb16e074", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" }
    ],
    price: 2800,
    location: "Hampi",
    country: "India",
    geometry: { type: "Point", coordinates: [76.4600, 15.3350] },
    category: "Heritage",
    propertyType: "Homestay",
    amenities: ["WiFi", "River View", "Parking", "Garden"],
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No loud music", "Respect heritage site", "No littering"],
    cancellationPolicy: "Flexible",
    cleaningFee: 600,
    serviceFee: 400,
    isAvailable: true,
    accessibilityNotes: "Flat ground access.",
    checkInInstructions: "Host will greet at property."
  },

  {
    title: "Hampi Heritage Homestay",
    description: "Traditional homestay surrounded by ancient ruins and local culture. Ideal for authentic Hampi experience.",
    image: { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" }
    ],
    price: 2200,
    location: "Hampi",
    country: "India",
    geometry: { type: "Point", coordinates: [76.4600, 15.3350] },
    category: "Heritage",
    propertyType: "Homestay",
    amenities: ["WiFi", "Parking", "Kitchen", "Garden"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No parties", "Respect host", "Quiet hours after 10PM"],
    cancellationPolicy: "Flexible",
    cleaningFee: 500,
    serviceFee: 300,
    isAvailable: true,
    accessibilityNotes: "Easily accessible.",
    checkInInstructions: "Host will share directions."
  },

  {
    title: "Boulder View Eco Stay",
    description: "Stay amidst Hampi’s iconic boulder landscape with eco-friendly rooms and scenic views.",
    image: { url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" }
    ],
    price: 3000,
    location: "Hampi",
    country: "India",
    geometry: { type: "Point", coordinates: [76.4550, 15.3300] },
    category: "Trending",
    propertyType: "Cabin",
    amenities: ["WiFi", "Bonfire", "Mountain View", "Parking"],
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No loud music", "No smoking indoors", "Respect nature"],
    cancellationPolicy: "Moderate",
    cleaningFee: 700,
    serviceFee: 500,
    isAvailable: true,
    accessibilityNotes: "Slight uneven terrain.",
    checkInInstructions: "Staff available on arrival."
  },

  {
    title: "Tungabhadra Riverside Camp",
    description: "A scenic campsite by the river with bonfire nights and open skies. Ideal for backpackers and explorers.",
    image: { url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" }
    ],
    price: 2500,
    location: "Hampi",
    country: "India",
    geometry: { type: "Point", coordinates: [76.4700, 15.3400] },
    category: "Trending",
    propertyType: "Tent/Glamping",
    amenities: ["Bonfire", "River View", "Parking", "Meals Included"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No littering", "No loud music after 10PM", "Follow campsite rules"],
    cancellationPolicy: "Moderate",
    cleaningFee: 600,
    serviceFee: 400,
    isAvailable: true,
    accessibilityNotes: "Short walk required.",
    checkInInstructions: "Camp staff will assist."
  },

  {
    title: "Hilltop Sunrise Guesthouse",
    description: "Enjoy panoramic sunrise views over Hampi ruins from this hilltop guesthouse.",
    image: { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" }
    ],
    price: 2700,
    location: "Hampi",
    country: "India",
    geometry: { type: "Point", coordinates: [76.4500, 15.3450] },
    category: "Heritage",
    propertyType: "Homestay",
    amenities: ["WiFi", "Mountain View", "Parking", "Kitchen"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No parties", "Quiet hours", "Respect surroundings"],
    cancellationPolicy: "Flexible",
    cleaningFee: 500,
    serviceFee: 300,
    isAvailable: true,
    accessibilityNotes: "Requires short climb.",
    checkInInstructions: "Directions shared prior."
  },

  {
    title: "Forest Edge Treehouse Retreat",
    description: "Stay high above the forest floor in a cozy treehouse surrounded by lush greenery. Perfect for couples looking for a unique nature escape.",
    image: { url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" }
    ],
    price: 4800,
    location: "Wayanad",
    country: "India",
    geometry: { type: "Point", coordinates: [76.1320, 11.6854] },
    category: "Forests",
    propertyType: "Treehouse",
    amenities: ["WiFi", "Forest View", "Bonfire", "Breakfast"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No loud music", "No littering", "Respect wildlife"],
    cancellationPolicy: "Moderate",
    cleaningFee: 900,
    serviceFee: 600,
    isAvailable: true,
    accessibilityNotes: "Access via stairs/ladder.",
    checkInInstructions: "Staff will assist on arrival."
  },

  {
    title: "Coffee Plantation Homestay",
    description: "Experience life inside a coffee plantation with fresh air and scenic views. Ideal for a calm and authentic stay.",
    image: { url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" }
    ],
    price: 3000,
    location: "Wayanad",
    country: "India",
    geometry: { type: "Point", coordinates: [76.1320, 11.6854] },
    category: "Farms",
    propertyType: "Farm Stay",
    amenities: ["WiFi", "Garden", "Parking", "Bonfire", "Meals"],
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    houseRules: ["No parties", "Respect plantation", "No littering"],
    cancellationPolicy: "Flexible",
    cleaningFee: 700,
    serviceFee: 500,
    isAvailable: true,
    accessibilityNotes: "Accessible via village road.",
    checkInInstructions: "Host will guide before arrival."
  },

  {
    title: "Luxury Jungle Pool Villa",
    description: "A premium villa hidden in the jungle with private pool and modern interiors. Ideal for luxury nature stays.",
    image: { url: "https://images.unsplash.com/photo-1613977257363-707ba9348227", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" }
    ],
    price: 12000,
    location: "Wayanad",
    country: "India",
    geometry: { type: "Point", coordinates: [76.1400, 11.7000] },
    category: "Trending",
    propertyType: "Villa",
    amenities: ["WiFi", "Pool", "AC", "Parking", "Kitchen"],
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 3,
    houseRules: ["No loud music after 10PM", "No pets", "ID required"],
    cancellationPolicy: "Strict",
    cleaningFee: 1800,
    serviceFee: 1200,
    isAvailable: true,
    accessibilityNotes: "Car accessible.",
    checkInInstructions: "Caretaker available on-site."
  },

  {
    title: "Misty Hills Wooden Cabin",
    description: "A cozy wooden cabin surrounded by misty hills and greenery. Perfect for a peaceful and quiet retreat.",
    image: { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" }
    ],
    price: 3500,
    location: "Wayanad",
    country: "India",
    geometry: { type: "Point", coordinates: [76.1200, 11.6900] },
    category: "Hill Stations",
    propertyType: "Cabin",
    amenities: ["WiFi", "Bonfire", "Mountain View", "Parking"],
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No loud music", "No smoking indoors", "Respect nature"],
    cancellationPolicy: "Flexible",
    cleaningFee: 700,
    serviceFee: 500,
    isAvailable: true,
    accessibilityNotes: "Slight uphill path.",
    checkInInstructions: "Directions shared before arrival."
  },

  {
    title: "Budget Garden View Homestay",
    description: "A simple and clean homestay with a beautiful garden view. Ideal for budget travelers exploring Wayanad.",
    image: { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" }
    ],
    price: 2200,
    location: "Wayanad",
    country: "India",
    geometry: { type: "Point", coordinates: [76.1300, 11.6800] },
    category: "Forests",
    propertyType: "Homestay",
    amenities: ["WiFi", "Parking", "Kitchen", "Garden"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No parties", "Respect host", "Quiet hours"],
    cancellationPolicy: "Flexible",
    cleaningFee: 500,
    serviceFee: 300,
    isAvailable: true,
    accessibilityNotes: "Ground floor access.",
    checkInInstructions: "Host will welcome guests."
  },

  {
    title: "French Quarter Heritage Villa",
    description: "Stay in a beautifully restored French-style villa in White Town. Enjoy pastel streets, cafes, and colonial charm right outside your door.",
    image: { url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" }
    ],
    price: 8500,
    location: "Pondicherry",
    country: "India",
    geometry: { type: "Point", coordinates: [79.8347, 11.9365] },
    category: "Heritage",
    propertyType: "Villa",
    amenities: ["WiFi", "AC", "Garden", "Parking", "Breakfast"],
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    houseRules: ["No loud music after 10PM", "No pets", "ID required"],
    cancellationPolicy: "Strict",
    cleaningFee: 1400,
    serviceFee: 1000,
    isAvailable: true,
    accessibilityNotes: "Ground floor accessible.",
    checkInInstructions: "Caretaker will assist on arrival."
  },

  {
    title: "Rock Beach Sea View Apartment",
    description: "Wake up to stunning sea views right from your balcony near Rock Beach. Perfect for a peaceful coastal stay.",
    image: { url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" }
    ],
    price: 4800,
    location: "Pondicherry",
    country: "India",
    geometry: { type: "Point", coordinates: [79.8350, 11.9400] },
    category: "Beaches",
    propertyType: "Apartment",
    amenities: ["WiFi", "AC", "Sea View", "Kitchen", "Parking"],
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No parties", "No smoking indoors", "Quiet hours after 11PM"],
    cancellationPolicy: "Moderate",
    cleaningFee: 900,
    serviceFee: 600,
    isAvailable: true,
    accessibilityNotes: "Lift available.",
    checkInInstructions: "Self check-in via keypad."
  },

  {
    title: "Auroville Eco Stay Homestay",
    description: "A serene eco-friendly Homestay near Auroville surrounded by greenery. Ideal for slow living and mindful travel.",
    image: { url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" }
    ],
    price: 3500,
    location: "Pondicherry",
    country: "India",
    geometry: { type: "Point", coordinates: [79.8070, 12.0060] },
    category: "Farms",
    propertyType: "Homestay",
    amenities: ["WiFi", "Garden", "Parking", "Breakfast"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No loud music", "No littering", "Respect environment"],
    cancellationPolicy: "Flexible",
    cleaningFee: 700,
    serviceFee: 500,
    isAvailable: true,
    accessibilityNotes: "Accessible via village road.",
    checkInInstructions: "Host will guide before arrival."
  },

  {
    title: "Beachside Boutique Homestay",
    description: "A cozy homestay just steps from Serenity Beach with modern interiors and a relaxed vibe.",
    image: { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" }
    ],
    price: 3000,
    location: "Pondicherry",
    country: "India",
    geometry: { type: "Point", coordinates: [79.8400, 11.9600] },
    category: "Beaches",
    propertyType: "Homestay",
    amenities: ["WiFi", "AC", "Parking", "Kitchen"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No parties", "No smoking indoors", "Respect neighbors"],
    cancellationPolicy: "Flexible",
    cleaningFee: 600,
    serviceFee: 400,
    isAvailable: true,
    accessibilityNotes: "Easy road access.",
    checkInInstructions: "Host will welcome guests."
  },

  {
    title: "Luxury Pool Villa Pondicherry",
    description: "A premium villa with private pool and stylish interiors, perfect for group stays and weekend getaways.",
    image: { url: "https://images.unsplash.com/photo-1613977257363-707ba9348227", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" }
    ],
    price: 11000,
    location: "Pondicherry",
    country: "India",
    geometry: { type: "Point", coordinates: [79.8200, 11.9200] },
    category: "Trending",
    propertyType: "Villa",
    amenities: ["WiFi", "Pool", "AC", "Parking", "Kitchen"],
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 3,
    houseRules: ["No loud music after 10PM", "No pets", "ID required"],
    cancellationPolicy: "Strict",
    cleaningFee: 1700,
    serviceFee: 1200,
    isAvailable: true,
    accessibilityNotes: "Car accessible.",
    checkInInstructions: "Caretaker will assist on arrival."
  },

  {
    title: "Kaza Valley Mountain Homestay",
    description: "A warm homestay in the heart of Kaza offering authentic Spitian hospitality. Enjoy stunning valley views and local meals.",
    image: { url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" }
    ],
    price: 2800,
    location: "Spiti Valley",
    country: "India",
    geometry: { type: "Point", coordinates: [78.0667, 32.2267] },
    category: "Hill Stations",
    propertyType: "Homestay",
    amenities: ["WiFi", "Heater", "Mountain View", "Meals"],
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No loud music", "Respect local culture", "No littering"],
    cancellationPolicy: "Flexible",
    cleaningFee: 700,
    serviceFee: 500,
    isAvailable: true,
    accessibilityNotes: "Accessible via rough mountain roads.",
    checkInInstructions: "Host will guide via call before arrival."
  },

  {
    title: "Langza Buddha View Homestay",
    description: "Stay near the iconic Buddha statue in Langza village with breathtaking high-altitude views.",
    image: { url: "https://images.unsplash.com/photo-1549887534-1541e9326642", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" }
    ],
    price: 2500,
    location: "Spiti Valley",
    country: "India",
    geometry: { type: "Point", coordinates: [78.1500, 32.3000] },
    category: "Heritage",
    propertyType: "Homestay",
    amenities: ["Heater", "Mountain View", "Local Meals", "Parking"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No loud music", "No smoking indoors", "Respect monastery culture"],
    cancellationPolicy: "Flexible",
    cleaningFee: 600,
    serviceFee: 400,
    isAvailable: true,
    accessibilityNotes: "Remote village access.",
    checkInInstructions: "Location shared before arrival."
  },

  {
    title: "Chandratal Lake Camping Experience",
    description: "Camp under the stars near Chandratal Lake with surreal night skies and raw nature all around.",
    image: { url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" }
    ],
    price: 3500,
    location: "Spiti Valley",
    country: "India",
    geometry: { type: "Point", coordinates: [77.6000, 32.4833] },
    category: "Trending",
    propertyType: "Tent/Glamping",
    amenities: ["Bonfire", "Meals Included", "Lake View", "Parking"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No littering", "Follow campsite rules", "No loud music"],
    cancellationPolicy: "Moderate",
    cleaningFee: 800,
    serviceFee: 600,
    isAvailable: true,
    accessibilityNotes: "High-altitude rough terrain.",
    checkInInstructions: "Camp coordinator will assist."
  },

  {
    title: "Tabo Monastery Stay",
    description: "Stay near the ancient Tabo Monastery and experience spiritual calm in the Himalayas.",
    image: { url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" }
    ],
    price: 2200,
    location: "Spiti Valley",
    country: "India",
    geometry: { type: "Point", coordinates: [78.3833, 32.0833] },
    category: "Pilgrimage",
    propertyType: "Homestay",
    amenities: ["Heater", "Simple Meals", "Parking", "Mountain View"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No alcohol", "Maintain silence", "Respect monastery rules"],
    cancellationPolicy: "Flexible",
    cleaningFee: 500,
    serviceFee: 300,
    isAvailable: true,
    accessibilityNotes: "Basic rural setup.",
    checkInInstructions: "Check-in via host."
  },

  {
    title: "Luxury Spiti Valley View Cabin",
    description: "A rare luxury stay in Spiti with modern comforts and panoramic valley views.",
    image: { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" }
    ],
    price: 9500,
    location: "Spiti Valley",
    country: "India",
    geometry: { type: "Point", coordinates: [78.0667, 32.2267] },
    category: "Trending",
    propertyType: "Cabin",
    amenities: ["WiFi", "Heater", "Mountain View", "Parking", "Hot Water"],
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    houseRules: ["No loud music", "No pets", "ID required"],
    cancellationPolicy: "Strict",
    cleaningFee: 1500,
    serviceFee: 1000,
    isAvailable: true,
    accessibilityNotes: "Car accessible but remote.",
    checkInInstructions: "Caretaker available."
  },

  {
    title: "Agatti Island Beach Villa",
    description: "A stunning beachfront villa with crystal clear lagoon views. Perfect for a peaceful island escape with luxury comfort.",
    image: { url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" }
    ],
    price: 12000,
    location: "Lakshadweep",
    country: "India",
    geometry: { type: "Point", coordinates: [72.1850, 10.8500] },
    category: "Beaches",
    propertyType: "Villa",
    amenities: ["WiFi", "AC", "Beach Access", "Sea View", "Meals"],
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    houseRules: ["No loud music", "ID required", "Follow island regulations"],
    cancellationPolicy: "Strict",
    cleaningFee: 1800,
    serviceFee: 1200,
    isAvailable: true,
    accessibilityNotes: "Accessible via boat transfer.",
    checkInInstructions: "Resort staff will assist on arrival."
  },

  {
    title: "Bangaram Island Luxury Beach Hut",
    description: "Stay in a private beach hut on Bangaram Island with turquoise waters and white sand beaches all around.",
    image: { url: "https://images.unsplash.com/photo-1519046904884-53103b34b206", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" }
    ],
    price: 14000,
    location: "Lakshadweep",
    country: "India",
    geometry: { type: "Point", coordinates: [72.2870, 10.9400] },
    category: "Trending",
    propertyType: "Beach House",
    amenities: ["WiFi", "AC", "Beach Access", "Sea View", "Breakfast"],
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No littering", "Respect marine life", "No loud music"],
    cancellationPolicy: "Strict",
    cleaningFee: 2000,
    serviceFee: 1500,
    isAvailable: true,
    accessibilityNotes: "Boat access only.",
    checkInInstructions: "Pickup arranged from jetty."
  },

  {
    title: "Kadmat Island Budget Beach Stay",
    description: "Affordable beachfront stay with clean rooms and direct beach access. Ideal for budget island travelers.",
    image: { url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560449752-3fd4b9b6b92f", filename: "listingimage" }
    ],
    price: 4500,
    location: "Lakshadweep",
    country: "India",
    geometry: { type: "Point", coordinates: [72.7800, 11.2200] },
    category: "Beaches",
    propertyType: "Homestay",
    amenities: ["WiFi", "Beach Access", "Meals", "Parking"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No alcohol", "Respect local rules", "No littering"],
    cancellationPolicy: "Moderate",
    cleaningFee: 800,
    serviceFee: 500,
    isAvailable: true,
    accessibilityNotes: "Island transport required.",
    checkInInstructions: "Host will assist on arrival."
  },

  {
    title: "Coral Reef View Eco Homestay",
    description: "Eco-friendly Homestay with views of coral reefs and clear lagoons. Perfect for nature lovers and divers.",
    image: { url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" }
    ],
    price: 6000,
    location: "Lakshadweep",
    country: "India",
    geometry: { type: "Point", coordinates: [72.6000, 11.0000] },
    category: "Beaches",
    propertyType: "Homestay",
    amenities: ["WiFi", "Sea View", "Eco Stay", "Meals", "Parking"],
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    houseRules: ["No plastic waste", "Respect marine life", "No loud music"],
    cancellationPolicy: "Moderate",
    cleaningFee: 900,
    serviceFee: 600,
    isAvailable: true,
    accessibilityNotes: "Boat access required.",
    checkInInstructions: "Resort team will coordinate arrival."
  },

  {
    title: "Premium Lagoon View Resort Stay",
    description: "Enjoy luxury island living with panoramic lagoon views, premium rooms, and curated experiences.",
    image: { url: "https://images.unsplash.com/photo-1613977257363-707ba9348227", filename: "listingimage" },
    images: [
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae", filename: "listingimage" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267", filename: "listingimage" }
    ],
    price: 13500,
    location: "Lakshadweep",
    country: "India",
    geometry: { type: "Point", coordinates: [72.2000, 10.9000] },
    category: "Trending",
    propertyType: "Villa",
    amenities: ["WiFi", "Pool", "AC", "Sea View", "Meals", "Parking"],
    maxGuests: 5,
    bedrooms: 2,
    bathrooms: 2,
    houseRules: ["No loud music", "ID required", "Follow resort rules"],
    cancellationPolicy: "Strict",
    cleaningFee: 2000,
    serviceFee: 1500,
    isAvailable: true,
    accessibilityNotes: "Boat transfer required.",
    checkInInstructions: "Pickup arranged by resort."
  },
];

module.exports = { data: sampleListings };